version: '3'
services:
  load_balancer:
    build: .
    ports:
      - "5000:5000"
  server1:
    build: .
    environment:
      - SERVER_ID=1
  server2:
    build: .
    environment:
      - SERVER_ID=2
  server3:
    build: .
    environment:
      - SERVER_ID=3
